### PR TITLE
Implement total deduplication size

### PR DESCRIPTION
**Pull request by 0xdeafbeef**

### CODE REVIEW

**Comment by kornelski** [comment]
This is hard to review. Please don't create unnecessary changes with rustfmt.

**Comment by 0xd34b33f** [comment]
Ok, sorry. I'll fix it. Why no rust format?

**Comment by kornelski** [comment]
Because rust  
&nbsp; &nbsp;  fmt  
&nbsp; &nbsp;  makes   
&nbsp; &nbsp;  expressions
&nbsp; &nbsp;  ridiculously  
&nbsp; &nbsp;  divided   
&nbsp; &nbsp;  into   
&nbsp; &nbsp;  lines

**Comment by 0xd34b33f** [comment]
Fixed

**Comment by kornelski** [comment]
Thanks, now I can see the change!

And sadly, it's not valid. The problem here are hardlink groups.

When you have files:

* A -> inode A
* B -> inode A
* C -> inode A
* D -> inode D
* E -> inode D

then you have 5 files, linked to two inodes. The tool will show two dupes (D, E), but disk space savings are only from removal of one inode (D).


* A -> inode A
* B -> inode A
* C -> inode A
* D -> inode A // dupe
* E -> inode A // dupe

**Comment by 0xd34b33f** [comment]
So, maybe I should calculate it on different step? Or it's shown in final vector?

**Comment by kornelski** [comment]
I'm not entirely sure, because I haven't fully thought that through, but I think the correct implementation would be based on number of `FileSet` objects that were eliminated (each `FileSet` represents a set of paths that point to the same inode).

There's also an edge case where fileset may contain fewer paths than hardlink count of that inode, because there exist other paths outside of directories that were scanned.

**Pull request closed without merging**
